# Generated by Django 5.2.1 on 2025-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0003_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Failed', max_length=20),
        ),
    ]
