# Generated by Django 5.2.1 on 2025-10-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0003_category_products_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
