# Generated by Django 5.2.1 on 2025-11-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0004_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
