# Generated by Django 5.2.1 on 2025-10-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0006_cart_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_id',
        ),
    ]
