# Generated by Django 5.2.1 on 2025-10-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0007_rename_product_cart_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
